[package]
name = "souq"
version = "0.0.1"

[build]
target-dir = "Target"

[lib]
name = "souq"
path = "Source/Library/main.rs"

[[bin]]
name = "souq"
path = "Source/Binary/souq.rs"

[dependencies]
unbug = { version = "0.2.0", features = ["enable"] }

[features]
default = []
Debug = ["unbug/enable"]
